=== melvinwallerjr/vtcalendar/trunk/dev/configs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:element name="Configs">
		<xs:annotation>
			<xs:documentation>Configurable parameters for VTCalendar.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Section" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Section">
		<xs:annotation>
			<xs:documentation>Configuration is segmented into one or more human-readable sections.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Config" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="Label" type="Label" use="required">
				<xs:annotation>
					<xs:documentation>TODO</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Config">
		<xs:annotation>
			<xs:documentation>A variable that can be changed to modify the way VTCalendar works.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				
				<xs:element name="Default" minOccurs="0">
					<xs:annotation>
						<xs:documentation>
							The default value for the config.
							This value is automatically typed/selected in the installation form, and
							if this config is missing from config.inc.php this is the value that is set.
						</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="Internal" type="xs:string">
									<xs:annotation>
										<xs:documentation>Override the default value for config-defaults.inc.php. It is not used in the installation form.</xs:documentation>
									</xs:annotation>
								</xs:attribute>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="Example" type="RequiredString" minOccurs="0">
					<xs:annotation>
						<xs:documentation>A human-readable example value for this config.</xs:documentation>
					</xs:annotation>
				</xs:element>
				
				<xs:element name="Choices" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Including this element turns this config into a drop-down menu in the installation form.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Choice" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>One of the possible values for the drop-down menu.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="RequiredString">
											<xs:attribute name="Value" type="xs:string"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="Comment" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Human-readable text that describes what this config does.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Line" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>A single line in the comment.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="Hidden" type="xs:boolean" default="false">
												<xs:annotation>
													<xs:documentation>
														Hide the comment line in the installation form.
														It will still show in config.inc.php and config-defaults.inc.php.
													</xs:documentation>
												</xs:annotation>
											</xs:attribute>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="Dependants" minOccurs="0">
					<xs:annotation>
						<xs:documentation>
							Only applies with this config is of type 'boolean'.
							One or more config that are dependant on this config being set to true.
						</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Config" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			
			<xs:attribute name="Label" type="Label" use="required">
				<xs:annotation>
					<xs:documentation>TODO</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="Variable" type="Variable">
				<xs:annotation>
					<xs:documentation>TODO</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="Type" type="Type">
				<xs:annotation>
					<xs:documentation>TODO</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="Required" type="xs:boolean">
				<xs:annotation>
					<xs:documentation>TODO</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="IsDefinition" type="xs:boolean" default="true">
				<xs:annotation>
					<xs:documentation>TODO</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	
	<xs:simpleType name="RequiredString">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="Label">
		<xs:restriction base="xs:string">
			<xs:pattern value="[^a-z][^\n\r]+"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="Variable">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z_0-9]+"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="Type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="boolean"/>
			<xs:enumeration value="string"/>
			<xs:enumeration value="multiline"/>
			<xs:enumeration value="number"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== melvinwallerjr/vtcalendar/trunk/dev/configs.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="configs.xsd">
    <Section Label="General">
        <Config Label="Title Prefix" Variable="TITLEPREFIX" Type="string">
            <Comment>
                <Line>OPTIONAL. Added at the beginning of the &lt;title&gt; tag.</Line>
            </Comment>
        </Config>
        <Config Label="Title Suffix" Variable="TITLESUFFIX" Type="string">
            <Example>" - My University"</Example>
            <Comment>
                <Line>OPTIONAL. Added at the end of the &lt;title&gt; tag.</Line>
            </Comment>
        </Config>
        <Config Label="Language" Variable="LANGUAGE" Type="string" Required="true">
            <Default>en</Default>
        	<Example>en (English), de (German), sv (Swedish)</Example>
            <Comment>
                <Line>Language used (refers to language file in directory /languages)</Line>
            </Comment>
        </Config>
    	<Config Label="Max Year Ahead for New Events" Variable="ALLOWED_YEARS_AHEAD" Type="number">
    		<Default>3</Default>
    		<Comment>
    			<Line>The number of years into the future that the calendar will allow users to create events for.</Line>
    			<Line ForceBreak="true">For example, if the current year is 2000 then a value of '3' will allow users to create events up to 2003.</Line>
    		</Comment>
    	</Config>
    </Section>
    <Section Label="Database">
    	<Config Label="Database Connection String" Variable="DATABASE" Type="string" Required="true">
        	<Example>mysql://vtcal:abc123@localhost/vtcalendar</Example>
    		<Comment>
    			<Line>This is the database connection string used by the PEAR library.</Line>
    			<Line ForceBreak="true">It has the format: "mysql://user:password@host/databasename" or "pgsql://user:password@host/databasename"</Line>
            </Comment>
    	</Config>
    	<Config Label="Schema Name" Variable="SCHEMANAME" Type="string" Required="false">
    		<Example>public</Example>
    		<Comment>
    			<Line>In some databases (such as PostgreSQL) you may have multiple sets of VTCalendar tables within the same database, but in different schemas.</Line>
    			<Line>If this is the case for you, enter the name of the schema here.</Line>
    			<Line>It will be prefixed to the table name like so: SCHEMANAME.vtcal_calendars.</Line>
    			<Line>If necessary quote the schema name using a backtick (`) for MySQL or double quotes (") for PostgreSQL.</Line>
    			<Line>Note: If specified, the table prefix MUST end with a period.</Line>
    		</Comment>
    	</Config>
        <Config Label="SQL Log File" Variable="SQLLOGFILE" Type="string">
            <Example>/var/log/vtcalendarsql.log</Example>
            <Comment>
                <Line>OPTIONAL. Put a name of a (folder and) file where the calendar logs every SQL query to the database.</Line>
                <Line>This is good for debugging but make sure you write into a file that's not readable by the webserver or else you may expose private information.</Line>
                <Line>If left blank ("") no log will be kept. That's the default.</Line>
            </Comment>
        </Config>
    </Section>
    <Section Label="Authentication">
    	<Config Label="User ID Regular Expression" Variable="REGEXVALIDUSERID" Type="string" Required="true">
            <Default>/^[A-Za-z][\._A-Za-z0-9\-\\]{1,49}$/</Default>
            <Comment>
                <Line>This regular expression defines what is considered a valid user-ID.</Line>
            </Comment>
        </Config>
        <Config Label="Database Authentication" Variable="AUTH_DB" Type="boolean">
            <Default>true</Default>
            <Comment>
                <Line>Authenticate users against the database.</Line>
                <Line>If enabled, this is always performed before any other authentication.</Line>
            </Comment>
            <Dependants>
                <Config Label="Prefix for Database Usernames" Variable="AUTH_DB_USER_PREFIX" Type="string">
                    <Example>db_</Example>
                    <Comment>
                        <Line>OPTIONAL. This prefix is used when creating/editing a local user-ID (in the DB "user" table), e.g. "calendar."</Line>
                        <Line>If you only use auth_db just leave it an empty string.</Line>
                        <Line>Its purpose is to avoid name-space conflicts with the users authenticated via LDAP or HTTP.</Line>
                    </Comment>
                </Config>
                <Config Label="Database Authentication Notice" Variable="AUTH_DB_NOTICE" Type="string">
                    <Comment>
                        <Line>OPTIONAL. This displays a text (or nothing) on the Update tab behind the user user management options.</Line>
                        <Line>It could be used if you employ both, AUTH_DB and AUTH_LDAP at the same time to let users know that they should create local users only if they are not in the LDAP.</Line>
                    </Comment>
                </Config>
                <!--<Config Label="Create Main Admin Account" Variable="AUTH_DB_CREATEADMIN" Type="boolean" IsDefinition="false">
                    <Default>true</Default>
                    <Comment>
                        <Line>If the database has not yet been populated, you will need to create a main admin account in order to administer the calendar.</Line>
                        <Line>However, if you are using LDAP or HTTP authentication this will not be necessary assuming you specify main admin account names under those sections.</Line>
                    </Comment>
                    <Dependants>
                        <Config Label="Main Admin Username" Variable="AUTH_DB_CREATEADMIN_USERNAME" Type="string" Required="true" IsDefinition="false">
                            <Example>root</Example>
                        </Config>
                        <Config Label="Main Admin Password" Variable="AUTH_DB_CREATEADMIN_PASSWORD" Type="string" Required="true" IsDefinition="false"/>
                    </Dependants>
                </Config>-->
            </Dependants>
        </Config>
        <Config Label="LDAP Authentication" Variable="AUTH_LDAP" Type="boolean">
            <Default>false</Default>
            <Comment>
                <Line>Authenticate users against a LDAP server.</Line>
                <Line>If enabled, HTTP authenticate will be ignored.</Line>
            </Comment>
            <Dependants>
                <Config Label="Verify LDAP Settings" Variable="LDAP_CHECK" Type="boolean" IsDefinition="false">
                    <Default>true</Default>
                    <Comment>
                        <Line>Check this box if you would like to verify the LDAP settings when submitting this form.</Line>
                        <Line>Uncheck this box if you know the settings are correct, but your LDAP server is currently unavailable.</Line>
                    </Comment>
                </Config>
                <Config Label="LDAP Host Name" Variable="LDAP_HOST" Type="string" Required="true">
            	    <Example>directory.myuniversity.edu or ldap://directory.myuniversity.edu/ or ldaps://secure-directory.myuniversity.edu/</Example>
            	    <Comment>
            	        <Line>If you are using OpenLDAP 2.x.x you can specify a URL ('ldap://host/') instead of the hostname ('host').</Line>
            	    </Comment>
            	</Config>
                <Config Label="LDAP Port" Variable="LDAP_PORT" Type="number">
                    <Default>389</Default>
                    <Comment>
                        <Line>The port to connect to. Ignored if LDAP Host Name is a URL.</Line>
                    </Comment>
                </Config>
            	<Config Label="LDAP Username Attribute" Variable="LDAP_USERFIELD" Type="string" Required="true">
                    <Example>sAMAccountName</Example>
                    <Comment>
                        <Line>The attribute which contains the username.</Line>
                    </Comment>
                </Config>
            	<Config Label="LDAP Base DN" Variable="LDAP_BASE_DN" Type="string" Required="true">
                    <Example>DC=myuniversity,DC=edu</Example>
                </Config>
                <Config Label="Additional LDAP Search Filter" Variable="LDAP_SEARCH_FILTER" Type="string">
                    <Example>(objectClass=person)</Example>
                    <Comment>
                        <Line>OPTIONAL. A filter to add to the LDAP search.</Line>
                    </Comment>
                </Config>
                <Config Label="Authenticate When Connecting to LDAP" Variable="LDAP_BIND" Type="boolean" IsDefinition="false">
                    <Default>false</Default>
                    <Comment>
                        <Line>Before authenticating the user, we first check if the username exists.</Line>
                        <Line>If your LDAP server does not allow anonymous searches, you will need to specify a username and password to bind as.</Line>
                    </Comment>
                    <Dependants>
                        <Config Label="LDAP Username" Variable="LDAP_BIND_USER" Type="string" Required="true">
                            <Comment>
                                <Line Hidden="true">Before authenticating the user, we first check if the username exists.</Line>
                                <Line Hidden="true">If your LDAP server does not allow anonymous connections, specific a username here.</Line>
                                <Line Hidden="true">Leave this blank to connect anonymously.</Line>
                            </Comment>
                        </Config>
